### ISSUE TITLE
Unable to view generated docs

### ISSUE THREAD

**Issue by iantrich** [m7r/grunt-ngdocs#148]
This is most likely user error, but I am unable to view my generated docs properly.

My docs are being generated properly into /docs and I can view them all individually but when trying to view the angular app ```'http://localhost:9001/docs'``` I get the message: ```'Cannot GET /docs'```

I'm very new to front-end dev so please forgive my ignorance. I'm just using the default setup in my gruntfile:

```
ngdocs: {
  all: ['app/**/*.js']
}
```

So everything else is on default. Thanks for your help on this.

Angular: 1.3.15
ngDocs: 0.2.7

- Ian

**Comment by CautemocSg** [comment]
I am also having this issue.

1) The docs folder is being generated on the same level as the app folder and Gruntfile
2) Running `grunt ngdocs` generates the docs folder with what appears to be the appropriate file structure:
```
css
font
grunt-scripts (contains my js files)
js
partials
index.html
```
3) Simply opening the index.html from a browser will render the html, but throw Cross origin request errors due to nothing being served
4) `grunt serve` runs the app fine, **http://localhost:9000/docs** throws **Cannot GET /docs**

**Comment by jantimon** [comment]
#153 allows serving the docs without a server.

**Comment by m7r** [comment]
please try 0.2.8

**Comment by Gargaroz** [comment]
@jantimon Hi, although I'm able to serve from filesystem `index.html`, I'm still getting
```
XMLHttpRequest cannot load file:///C:/<file-path> Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource
```
even if both the `docs/partials` and `docs/partials/api` folders empty.

This is my ng-docs configuration
```
ngdocs: {
       options: {
           dest: 'docs',
           html5Mode: false,
           inlinePartials: true,
           scripts: [
               'bower_components/angular/angular.js',
               'bower_components/angular-animate/angular-animate.js'
           ]
       },
       api: {
           src: ['app/scripts/**/*.js'],
           title: 'Docs'
       }
    }
```


What am I doing wrong?
